apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: get-hello-world
  name: get-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: get-hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: get-hello-world
    spec:
      containers:
      - image: get-hello-world
        name: get-hello-world
        imagePullPolicy: Never
        env:
          - name: BACKEND_URL
            value: http://hello-world.default.svc.cluster.local:8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-world
    spec:
      containers:
      - image: hello-world
        name: hello-world
        imagePullPolicy: Never
