apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: get-hello-world
  labels:
    app: get-hello-world
spec:
  rules:
  - host: get-hello-world.k8s.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: get-hello-world
            port:
              number: 8000
