apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: hello-world
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: get-hello-world
  name: get-hello-world
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: get-hello-world
  type: ClusterIP
